import HomePageTwo from './home-2/page'
export const metadata = {
  title: 'Protool',
  description: 'Generated by StaticMania',
}
export default function Home() {
  return (
    <>
      <HomePageTwo />
      {/* <Hero />
      <Clients />
      <Services />
      <Counter />
      <Vision />
      <Solution />
      <Integration />
      <FAQ />
      <Testimonial />
      <HomeBlog />
      <HomeCta /> */}
    </>
  )
}
